steps:
  # 1. Construir la imagen (Creando los .env vacíos para engañar a Java)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        touch .env && \
        touch src/main/resources/.env && \
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/sigea-repo/sigea-backend:$SHORT_SHA .


  # 2. Subir la imagen al registro
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/sigea-repo/sigea-backend:$SHORT_SHA']

  # 3. Actualizar Cloud Run (Solo cambiamos la imagen, MANTENEMOS las variables de Brevo y BD)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sigea-backend-dev'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sigea-repo/sigea-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sigea-repo/sigea-backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY